### PR TITLE
added the splash screen

### PR DESCRIPTION
**Pull request by EANimesha**
Added the splash screen
Issue #1 
@valtlfelipe can you check please?

### CODE REVIEW

**Comment by valtlfelipe** [comment]
Thanks for your PR! And sorry for the delay reviewing it!

It looks awesome, just one detail, the app is now fullscreen, to disable this please set this `android_disable_fullscreen: true` and then we are ready to rock!

**Comment by valtlfelipe** [comment]
Also, there is a bug in setting this config, we need to remove this line `<item name="android:windowFullscreen">true</item>` inside `android/app/src/main/res/values/styles.xml`

**Comment by EANimesha** [comment]
> Also, there is a bug in setting this config, we need to remove this line `<item name="android:windowFullscreen">true</item>` inside `android/app/src/main/res/values/styles.xml`

@valtlfelipe done updates

**Review by valtlfelipe — APPROVED** [review]
Awesome! Thanks

**Pull request merged**
